### ISSUE TITLE
“登录”和“登陆”

### ISSUE THREAD

**Issue by xyqlx** [NingYuanLin/cau_auth#1]
https://github.com/NingYuanLin/cau_auth/blob/8f84ae6288ba50b0e58fc4ed0d12b163675bb103/cau_auth/cau.py#L23-L41

建议统一为“登录”（<https://www.zhihu.com/question/19570377>）

**Comment by NingYuanLin** [comment]
OK~ [#b613886](https://github.com/NingYuanLin/cau_auth/commit/b613886384d478128a9a24567c3f12e2466591be)
